name: "Redirects in renamed files"
"on":
  pull_request:
    branches:
      - master

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          include_all_old_new_renamed_files: true
          files: |
            docs/**
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check renamed files
        id: missing_redirection
        env:
          ALL_OLD_AND_NEW_RENAMED_FILES: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
        run: |
          for file in ${{ steps.changed-files.outputs.renamed_files }};
          do
            if [ "${file: -4}" == ".rst" ]
              file="$file" | sed -e 's/\.[^.]*$//'
              then
                var="$var $file"
            fi
          done
          echo "$var"
          if ! [ -z "$var" ];then
            python "aiven/scripts/check_renamed_files.py" --renamed_files ${{ steps.changed-files.outputs.renamed_files }}
          fi

      - name: Check env
        if: ${{env.MISSING_REDIRECTION}} != ""
        run: |
          echo "renamed:"
          echo ${{env.MISSING_REDIRECTION}}
          echo "::error::Files were renamed with missing _redirects. Add redirect to renamed files to fix it. \n  ${{env.MISSING_REDIRECTION}}"
          exit 1

#check_renamed_files.py --renamed_files ${{ steps.changed-files.outputs.renamed_files }}

