name: "LinkCheck - Changed files"
"on":
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: null

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linkcheck on .rst files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ "${file: -4}" == ".rst" ]
              then
                var="$var $file"
            fi
          done
          echo $var
          if [ -z "$var" ]
          then
                echo "No *.rst changed files to check."
          else
                make files="$var" linkcheck-specified-files
          fi
